Traceback (most recent call last):
  File "/Users/franciscoescolano/miniconda3/envs/graphy/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/franciscoescolano/miniconda3/envs/graphy/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/franciscoescolano/miniconda3/envs/graphy/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/franciscoescolano/miniconda3/envs/graphy/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/franciscoescolano/miniconda3/envs/graphy/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/franciscoescolano/miniconda3/envs/graphy/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/franciscoescolano/miniconda3/envs/graphy/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from xyz2graph import MolGraph, to_networkx_graph, to_plotly_figure
from plotly.offline import init_notebook_mode, iplot
import networkx as nx
import pandas as pd

# initiate the Plotly notebook mode
init_notebook_mode(connected=True)

structures = pd.read_csv(PATH + 'structures.csv')
mol_names = structures.molecule_name.unique()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 9[0m
[1;32m      6[0m [38;5;66;03m# initiate the Plotly notebook mode[39;00m
[1;32m      7[0m init_notebook_mode(connected[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m----> 9[0m structures [38;5;241m=[39m pd[38;5;241m.[39mread_csv([43mPATH[49m [38;5;241m+[39m [38;5;124m'[39m[38;5;124mstructures.csv[39m[38;5;124m'[39m)
[1;32m     10[0m mol_names [38;5;241m=[39m structures[38;5;241m.[39mmolecule_name[38;5;241m.[39munique()

[0;31mNameError[0m: name 'PATH' is not defined

